name: Feature Request
description: Submit a feature request
title: "[Feature] Brief Title of the Feature"
body:
  - type: dropdown
    id: will-contribute
    attributes:
      label: Willing to Help Develop?
      description: If you plan to help with the development of this feature, please let us know so we can coordinate efforts.
      options:
        - "No"
        - "Yes"
        - Maybe
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for submitting this feature request! Please provide as much detail as possible to help us understand your needs.
  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: How can we contact you if we need more information?
      placeholder: E.g., email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please describe the feature you would like to request or the improvements you suggest.
      placeholder: E.g., Would like to add support for a specific API integration or a new settings option.
      value: "I would like to add a new feature..."
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Please provide context or scenarios where this feature would be used, helping us understand its need.
      placeholder: E.g., A feature for automating reports or enhancing accessibility.
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Feature Priority
      options:
        - High
        - Medium
        - Low
      description: Please specify the priority for this feature.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: If you have any extra details or resources, please provide them here.
      placeholder: Provide related links or documents.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow the project's code of conduct.
      options:
        - label: I agree to follow the project's code of conduct
          required: true
